//Order by Most traded currencies: https://en.wikipedia.org/wiki/Template:Most_traded_currencies
List<Map<String, dynamic>> currencies = [
  {
    "code": "USD",
    "name": "United States Dollar",
    "symbol": "\$",
    "flag": "USD",
  },
  {
    "code": "EUR",
    "name": "Euro",
    "symbol": "€",
    "flag": "EUR",
  },
  {
    "code": "JPY",
    "name": "Japanese Yen",
    "symbol": "¥",
    "flag": "JPY",
  },
  {
    "code": "GBP",
    "name": "British Pound",
    "symbol": "£",
    "flag": "GBP",
  },
  {
    "code": "AUD",
    "name": "Australian Dollar",
    "symbol": "\$",
    "flag": "AUD",
  },
  {
    "code": "CAD",
    "name": "Canadian Dollar",
    "symbol": "\$",
    "flag": "CAD",
  },
  {
    "code": "CHF",
    "name": "Switzerland Franc",
    "symbol": "CHF",
    "flag": "CHF",
  },
  {
    "code": "CNY",
    "name": "China Yuan Renminbi",
    "symbol": "¥",
    "flag": "CNY",
  },
  {
    "code": "HKD",
    "name": "Hong Kong Dollar",
    "symbol": "\$",
    "flag": "HKD",
  },
  {
    "code": "NZD",
    "name": "New Zealand Dollar",
    "symbol": "\$",
    "flag": "NZD",
  },
  {
    "code": "SEK",
    "name": "Sweden Krona",
    "symbol": "kr",
    "flag": "SEK",
  },
  {
    "code": "KRW",
    "name": "South Korea Won",
    "symbol": "₩",
    "flag": "KRW",
  },
  {
    "code": "SGD",
    "name": "Singapore Dollar",
    "symbol": "\$",
    "flag": "SGD",
  },
  {
    "code": "NOK",
    "name": "Norway Krone",
    "symbol": "kr",
    "flag": "NOK",
  },
  {
    "code": "MXN",
    "name": "Mexico Peso",
    "symbol": "\$",
    "flag": "MXN",
  },
  {
    "code": "INR",
    "name": "Indian Rupee",
    "symbol": "₹",
    "flag": "INR",
  },
  {
    "code": "RUB",
    "name": "Russia Ruble",
    "symbol": "₽",
    "flag": "RUB",
  },
  {
    "code": "ZAR",
    "name": "South Africa Rand",
    "symbol": "R",
    "flag": "ZAR",
  },
  {
    "code": "TRY",
    "name": "Turkish Lira",
    "symbol": "₺",
    "flag": "TRY",
  },
  {
    "code": "BRL",
    "name": "Brazilian Real",
    "symbol": "R\$",
    "flag": "BRL",
  },
  {
    "code": "TWD",
    "name": "Taiwan New Dollar",
    "symbol": "NT\$",
    "flag": "TWD",
  },
  {
    "code": "DKK",
    "name": "Denmark Krone",
    "symbol": "kr",
    "flag": "DKK",
  },
  {
    "code": "PLN",
    "name": "Poland Zloty",
    "symbol": "zł",
    "flag": "PLN",
  },
  {
    "code": "THB",
    "name": "Thailand Baht",
    "symbol": "฿",
    "flag": "THB",
  },
  {
    "code": "IDR",
    "name": "Indonesia Rupiah",
    "symbol": "Rp",
    "flag": "IDR",
  },
  {
    "code": "HUF",
    "name": "Hungary Forint",
    "symbol": "Ft",
    "flag": "HUF",
  },
  {
    "code": "CZK",
    "name": "Czech Koruna",
    "symbol": "Kč",
    "flag": "CZK",
  },
  {
    "code": "ILS",
    "name": "Israel Shekel",
    "symbol": "₪",
    "flag": "ILS",
  },
  {
    "code": "CLP",
    "name": "Chile Peso",
    "symbol": "\$",
    "flag": "CLP",
  },
  {
    "code": "PHP",
    "name": "Philippines Peso",
    "symbol": "₱",
    "flag": "PHP",
  },
  {
    "code": "AED",
    "name": "Emirati Dirham",
    "symbol": "د.إ",
    "flag": "AED",
  },
  {
    "code": "COP",
    "name": "Colombia Peso",
    "symbol": "\$",
    "flag": "COP",
  },
  {
    "code": "SAR",
    "name": "Saudi Arabia Riyal",
    "symbol": "﷼",
    "flag": "SAR",
  },
  {
    "code": "MYR",
    "name": "Malaysia Ringgit",
    "symbol": "RM",
    "flag": "MYR",
  },
  {
    "code": "RON",
    "name": "Romania Leu",
    "symbol": "L",
    "flag": "RON",
  },
  {
    "code": "AFN",
    "name": "Afghanistan Afghani",
    "symbol": "؋",
    "flag": "AFN",
  },
  {
    "code": "ALL",
    "name": "Albanian Lek",
    "symbol": "Lek",
    "flag": "ALB",
  },
  {
    "code": "DZD",
    "name": "Algerian dinar",
    "symbol": "دج",
    "flag": "DZ",
  },
  {
    "code": "ARS",
    "name": "Argentine Peso",
    "symbol": "\$",
    "flag": "ARS",
  },
  {
    "code": "AMD",
    "name": "Armenian Dram",
    "symbol": "֏",
    "flag": "AM",
  },
  {
    "code": "AZN",
    "name": "Azerbaijani Manat",
    "symbol": "₼",
    "flag": "AZE",
  },
  {
    "code": "BHD",
    "name": "Bahraini Dinar",
    "symbol": "BD",
    "flag": "BHD",
  },
  {
    "code": "BDT",
    "name": "Bangladeshi Taka",
    "symbol": " Tk",
    "flag": "BDT",
  },
  {
    "code": "BBD",
    "name": "Barbados Dollar",
    "symbol": "\$",
    "flag": "BBD",
  },
  {
    "code": "BYN",
    "name": "Belarussian Ruble",
    "symbol": "Br",
    "flag": "BY",
  },
  {
    "code": "BZD",
    "name": "Belize Dollar",
    "symbol": "BZ\$",
    "flag": "BZD",
  },
  {
    "code": "BMD",
    "name": "Bermuda Dollar",
    "symbol": "\$",
    "flag": "BMD",
  },
  {
    "code": "BTN",
    "name": "Bhutanese Ngultrum",
    "symbol": "Nu.",
    "flag": "BTN",
  },
  {
    "code": "BOB",
    "name": "Bolivia Bolíviano",
    "symbol": "\$b",
    "flag": "BOB",
  },
  {
    "code": "BAM",
    "name": "Bosnia convertible mark",
    "symbol": "KM",
    "flag": "BA",
  },
  {
    "code": "BWP",
    "name": "Botswanan Pula",
    "symbol": "P",
    "flag": "BW",
  },
  {
    "code": "BND",
    "name": "Brunei Darussalam Dollar",
    "symbol": "\$",
    "flag": "BND",
  },
  {
    "code": "BGN",
    "name": "Bulgarian Lev",
    "symbol": "лв",
    "flag": "BGN",
  },
  {
    "code": "BIF",
    "name": "Burundian Franc",
    "symbol": "FBu",
    "flag": "BI",
  },
  {
    "code": "KHR",
    "name": "Cambodian riel",
    "symbol": "៛",
    "flag": "KHM",
  },
  {
    "code": "KYD",
    "name": "Cayman Islands Dollar",
    "symbol": "\$",
    "flag": "KYD",
  },
  {
    "code": "XAF",
    "name": "Central African CFA franc",
    "symbol": "FCFA",
    "flag": null,
  },
  {
    "code": "XOF",
    "name": "UEMOA CFA franc",
    "symbol": "FCFA",
    "flag": "xof.png",
  },
  {
    "code": "CDF",
    "name": "Congolese franc",
    "symbol": "FC",
    "flag": "CD",
  },
  {
    "code": "CRC",
    "name": "Costa Rica Colon",
    "symbol": "₡",
    "flag": "CRC",
  },
  {
    "code": "DOP",
    "name": "Dominican Republic Peso",
    "symbol": "RD\$",
    "flag": "DOP",
  },
  {
    "code": "EGP",
    "name": "Egypt Pound",
    "symbol": "£",
    "flag": "EGP",
  },
  {
    "code": "ETB",
    "name": "Ethiopian Birr",
    "symbol": "Br",
    "flag": "ETB",
  },
  {
    "code": "GMD",
    "name": "Gambian dalasi",
    "symbol": "D",
    "flag": "GMD",
  },
  {
    "code": "GEL",
    "name": "Georgian Lari",
    "symbol": "₾",
    "flag": "GEL",
  },
  {
    "code": "GHS",
    "name": "Ghana Cedi",
    "symbol": "₵",
    "flag": "GHS",
  },
  {
    "code": "GTQ",
    "name": "Guatemalan quetzal",
    "symbol": "Q",
    "flag": "GT",
  },
  {
    "code": "GYD",
    "name": "Guyana Dollar",
    "symbol": "\$",
    "flag": "GYD",
  },
  {
    "code": "HTG",
    "name": "Haitian gourde",
    "symbol": "G",
    "flag": "HTI",
  },
  {
    "code": "ISK",
    "name": "Iceland Krona",
    "symbol": "kr",
    "flag": "ISK",
  },
  {
    "code": "JMD",
    "name": "Jamaica Dollar",
    "symbol": "J\$",
    "flag": "JMD",
  },
  {
    "code": "JOD",
    "name": "Jordanian dinar",
    "symbol": "د.أ",
    "flag": "JO",
  },
  {
    "code": "KZT",
    "name": "Kazakhstan Tenge",
    "symbol": "〒",
    "flag": "KZT",
  },
  {
    "code": "KES",
    "name": "Kenyan Shilling",
    "symbol": "KSh",
    "flag": "KES",
  },
  {
    "code": "KWD",
    "name": "Kuwaiti Dinar",
    "symbol": "د.ك",
    "flag": "KWD",
  },
  {
    "code": "KGS",
    "name": "Kyrgyzstani som",
    "symbol": "с",
    "flag": "KG",
  },
  {
    "code": "LAK",
    "name": "Laos Kip",
    "symbol": "₭",
    "flag": "LAK",
  },
  {
    "code": "LRD",
    "name": "Liberia Dollar",
    "symbol": "\$",
    "flag": "LRD",
  },
  {
    "code": "MKD",
    "name": "Macedonia Denar",
    "symbol": "ден",
    "flag": "MKD",
  },
  {
    "code": "MWK",
    "name": "Malawian Kwacha",
    "symbol": "MK",
    "flag": "MWK",
  },
  {
    "code": "MUR",
    "name": "Mauritius Rupee",
    "symbol": "₨",
    "flag": "MUR",
  },
  {
    "code": "MDL",
    "name": "Moldovan Leu",
    "symbol": "L",
    "flag": "MDL",
  },
  {
    "code": "MNT",
    "name": "Mongolia Tughrik",
    "symbol": "₮",
    "flag": "MNT",
  },
  {
    "code": "MAD",
    "name": "Moroccan Dirham",
    "symbol": "MAD",
    "flag": "MAD",
  },
  {
    "code": "MZN",
    "name": "Mozambique Metical",
    "symbol": "MT",
    "flag": "MZN",
  },
  {
    "code": "MMK",
    "name": "Myanmar Kyat",
    "symbol": "Ks",
    "flag": "MM",
  },
  {
    "code": "NAD",
    "name": "Namibia Dollar",
    "symbol": "\$",
    "flag": "NAD",
  },
  {
    "code": "NPR",
    "name": "Nepal Rupee",
    "symbol": "₨",
    "flag": "NPR",
  },
  {
    "code": "NIO",
    "name": "Nicaragua Cordoba",
    "symbol": "C\$",
    "flag": "NIO",
  },
  {
    "code": "NGN",
    "name": "Nigeria Naira",
    "symbol": "₦",
    "flag": "NGN",
  },
  {
    "code": "OMR",
    "name": "Oman Rial",
    "symbol": "﷼",
    "flag": "OMR",
  },
  {
    "code": "PKR",
    "name": "Pakistan Rupee",
    "symbol": "₨",
    "flag": "PKR",
  },
  {
    "code": "PGK",
    "name": "Papua New Guinean Kina",
    "symbol": "K",
    "flag": "PGK",
  },
  {
    "code": "PYG",
    "name": "Paraguay Guarani",
    "symbol": "₲",
    "flag": "PYG",
  },
  {
    "code": "PEN",
    "name": "Peru Sol",
    "symbol": "S/.",
    "flag": "PEN",
  },
  {
    "code": "QAR",
    "name": "Qatar Riyal",
    "symbol": "﷼",
    "flag": "QAR",
  },
  {
    "code": "RWF",
    "name": "Rwandan franc",
    "symbol": "FRw",
    "flag": "RWA",
  },
  {
    "code": "RSD",
    "name": "Serbia Dinar",
    "symbol": "Дин.",
    "flag": "RSD",
  },
  {
    "code": "SCR",
    "name": "Seychellois rupee",
    "symbol": "₨",
    "flag": "SC",
  },
  {
    "code": "SOS",
    "name": "Somalia Shilling",
    "symbol": "S",
    "flag": "SOS",
  },
  {
    "code": "LKR",
    "name": "Sri Lanka Rupee",
    "symbol": "₨",
    "flag": "LKR",
  },
  {
    "code": "SRD",
    "name": "Suriname Dollar",
    "symbol": "\$",
    "flag": "SRD",
  },
  {
    "code": "SYP",
    "name": "Syrian Lira",
    "symbol": "LS",
    "flag": "SYP",
  },
  {
    "code": "TZS",
    "name": "Tanzanian Shilling",
    "symbol": "TSh",
    "flag": "TZS",
  },
  {
    "code": "TTD",
    "name": "Trinidad and Tobago Dollar",
    "symbol": "TT\$",
    "flag": "TTD",
  },
  {
    "code": "TND",
    "name": "Tunisian dinar",
    "symbol": "د.ت",
    "flag": "TN",
  },
  {
    "code": "UGX",
    "name": "Ugandan Shilling",
    "symbol": "USh",
    "flag": "UGX",
  },
  {
    "code": "UAH",
    "name": "Ukraine Hryvnia",
    "symbol": "₴",
    "flag": "UAH",
  },
  {
    "code": "UYU",
    "name": "Uruguay Peso",
    "symbol": "\$U",
    "flag": "UYU",
  },
  {
    "code": "VEF",
    "name": "Venezuela Bolívar",
    "symbol": "Bs",
    "flag": "VEF",
  },
  {
    "code": "VND",
    "name": "Viet Nam Dong",
    "symbol": "₫",
    "flag": "VND",
  },
  {
    "code": "YER",
    "name": "Yemen Rial",
    "symbol": "﷼",
    "flag": "YER",
  },
  {
    "code": "ZMW",
    "name": "Zambian kwacha",
    "symbol": "ZK",
    "flag": "ZM",
  },
];
