//Order by Most traded currencies: https://en.wikipedia.org/wiki/Template:Most_traded_currencies
List<Map<String, dynamic>> currencies = [
  {
    "code": "USD",
    "name": "الدولار الأمريكي",
    "symbol": "\$",
    "flag": "USD",
  },
  {
    "code": "EUR",
    "name": "اليورو",
    "symbol": "€",
    "flag": "EUR",
  },
  {
    "code": "JPY",
    "name": "الين الياباني",
    "symbol": "¥",
    "flag": "JPY",
  },
  {
    "code": "GBP",
    "name": "الجنيه البريطاني",
    "symbol": "£",
    "flag": "GBP",
  },
  {
    "code": "AUD",
    "name": "الدولار الاسترالي",
    "symbol": "\$",
    "flag": "AUD",
  },
  {
    "code": "CAD",
    "name": "الدولار الكندي",
    "symbol": "\$",
    "flag": "CAD",
  },
  {
    "code": "CHF",
    "name": "الفرنك السويسري",
    "symbol": "CHF",
    "flag": "CHF",
  },
  {
    "code": "CNY",
    "name": "اليوان الصيني",
    "symbol": "¥",
    "flag": "CNY",
  },
  {
    "code": "HKD",
    "name": "دولار هونج كونج",
    "symbol": "\$",
    "flag": "HKD",
  },
  {
    "code": "NZD",
    "name": "الدولار النيوزيلندي",
    "symbol": "\$",
    "flag": "NZD",
  },
  {
    "code": "SEK",
    "name": "الكرونة السويدية",
    "symbol": "kr",
    "flag": "SEK",
  },
  {
    "code": "KRW",
    "name": "وون كوريا الجنوبية",
    "symbol": "₩",
    "flag": "KRW",
  },
  {
    "code": "SGD",
    "name": "الدولار السينغافوري",
    "symbol": "\$",
    "flag": "SGD",
  },
  {
    "code": "NOK",
    "name": "الكرونة النرويجية",
    "symbol": "kr",
    "flag": "NOK",
  },
  {
    "code": "MXN",
    "name": "البيزو المكسيكي",
    "symbol": "\$",
    "flag": "MXN",
  },
  {
    "code": "INR",
    "name": "الروبية الهندية",
    "symbol": "₹",
    "flag": "INR",
  },
  {
    "code": "RUB",
    "name": "الروبية الروسية",
    "symbol": "₽",
    "flag": "RUB",
  },
  {
    "code": "ZAR",
    "name": "راند جنوب أفريقيا",
    "symbol": "R",
    "flag": "ZAR",
  },
  {
    "code": "TRY",
    "name": "الليرة التركية",
    "symbol": "₺",
    "flag": "TRY",
  },
  {
    "code": "BRL",
    "name": "الريال البرازيلي",
    "symbol": "R\$",
    "flag": "BRL",
  },
  {
    "code": "TWD",
    "name": "الدولار التايواني",
    "symbol": "NT\$",
    "flag": "TWD",
  },
  {
    "code": "DKK",
    "name": "الكرونة الدينماركية",
    "symbol": "kr",
    "flag": "DKK",
  },
  {
    "code": "PLN",
    "name": "الزلوتي البولندي",
    "symbol": "zł",
    "flag": "PLN",
  },
  {
    "code": "THB",
    "name": "البات التايلاندي",
    "symbol": "฿",
    "flag": "THB",
  },
  {
    "code": "IDR",
    "name": "الروبية الإندونيسية",
    "symbol": "Rp",
    "flag": "IDR",
  },
  {
    "code": "HUF",
    "name": "الفورنت المجري",
    "symbol": "Ft",
    "flag": "HUF",
  },
  {
    "code": "CZK",
    "name": "الكرونة التشيكية",
    "symbol": "Kč",
    "flag": "CZK",
  },
  {
    "code": "ILS",
    "name": "الشيكل الإسرائيلي",
    "symbol": "₪",
    "flag": "ILS",
  },
  {
    "code": "CLP",
    "name": "البيزو التشيلي",
    "symbol": "\$",
    "flag": "CLP",
  },
  {
    "code": "PHP",
    "name": "البيزو الفلبيني",
    "symbol": "₱",
    "flag": "PHP",
  },
  {
    "code": "AED",
    "name": "الدرهم الإماراتي",
    "symbol": "د.إ",
    "flag": "AED",
  },
  {
    "code": "COP",
    "name": "البيزو الكولومبي",
    "symbol": "\$",
    "flag": "COP",
  },
  {
    "code": "SAR",
    "name": "الريال السعودي",
    "symbol": "﷼",
    "flag": "SAR",
  },
  {
    "code": "MYR",
    "name": "الرنجت الماليزي",
    "symbol": "RM",
    "flag": "MYR",
  },
  {
    "code": "RON",
    "name": "الليو الروماني",
    "symbol": "L",
    "flag": "RON",
  },
  {
    "code": "AFN",
    "name": "أفغاني",
    "symbol": "؋",
    "flag": "AFN",
  },
  {
    "code": "ALL",
    "name": "الليك الألباني",
    "symbol": "Lek",
    "flag": "ALB",
  },
  {
    "code": "DZD",
    "name": "الدينار الجزائري",
    "symbol": "دج",
    "flag": "DZ",
  },
  {
    "code": "ARS",
    "name": "البيزو الأرجنتيني",
    "symbol": "\$",
    "flag": "ARS",
  },
  {
    "code": "AMD",
    "name": "الدرام الأرميني",
    "symbol": "֏",
    "flag": "AM",
  },
  {
    "code": "AZN",
    "name": "المانات الأذربيجاني",
    "symbol": "₼",
    "flag": "AZE",
  },
  {
    "code": "BHD",
    "name": "الدينار البحريني",
    "symbol": "BD",
    "flag": "BHD",
  },
  {
    "code": "BDT",
    "name": "التاكا البنغلاديشي",
    "symbol": " Tk",
    "flag": "BDT",
  },
  {
    "code": "BBD",
    "name": "الدولار البربادوسي",
    "symbol": "\$",
    "flag": "BBD",
  },
  {
    "code": "BYN",
    "name": "الروبل البلاروسي",
    "symbol": "Br",
    "flag": "BY",
  },
  {
    "code": "BZD",
    "name": "الدولار البليزي",
    "symbol": "BZ\$",
    "flag": "BZD",
  },
  {
    "code": "BMD",
    "name": "الدولار البرمودي",
    "symbol": "\$",
    "flag": "BMD",
  },
  {
    "code": "BTN",
    "name": "النولترم البوتاني",
    "symbol": "Nu.",
    "flag": "BTN",
  },
  {
    "code": "BOB",
    "name": "البوليفيانو البوليفي",
    "symbol": "\$b",
    "flag": "BOB",
  },
  {
    "code": "BAM",
    "name": "المارك البوسني",
    "symbol": "KM",
    "flag": "BA",
  },
  {
    "code": "BWP",
    "name": "البولا البوتسواني",
    "symbol": "P",
    "flag": "BW",
  },
  {
    "code": "BND",
    "name": "الدولار البروني",
    "symbol": "\$",
    "flag": "BND",
  },
  {
    "code": "BGN",
    "name": "الليف البلغاري",
    "symbol": "лв",
    "flag": "BGN",
  },
  {
    "code": "BIF",
    "name": "الفرنك البورونديا",
    "symbol": "FBu",
    "flag": "BI",
  },
  {
    "code": "KHR",
    "name": "الريال الكمبودي",
    "symbol": "៛",
    "flag": "KHM",
  },
  {
    "code": "KYD",
    "name": "دولار جزر كايمان",
    "symbol": "\$",
    "flag": "KYD",
  },
  {
    "code": "XAF",
    "name": "فرنك وسط أفريقيا",
    "symbol": "FCFA",
    "flag": null,
  },
  {
    "code": "CDF",
    "name": "الفرنك الكونغولي",
    "symbol": "FC",
    "flag": "CD",
  },
  {
    "code": "CRC",
    "name": "الكولون الكوستاريكي",
    "symbol": "₡",
    "flag": "CRC",
  },
  {
    "code": "DOP",
    "name": "بيزو جمهورية الدومينيكان",
    "symbol": "RD\$",
    "flag": "DOP",
  },
  {
    "code": "EGP",
    "name": "الجنيه المصري",
    "symbol": "£",
    "flag": "EGP",
  },
  {
    "code": "ETB",
    "name": "البير الإثيوبي",
    "symbol": "Br",
    "flag": "ETB",
  },
  {
    "code": "GMD",
    "name": "الدالاسي الغامبي",
    "symbol": "D",
    "flag": "GMD",
  },
  {
    "code": "GEL",
    "name": "اللاري الجورجي",
    "symbol": "₾",
    "flag": "GEL",
  },
  {
    "code": "GHS",
    "name": "السيدي الغاني",
    "symbol": "₵",
    "flag": "GHS",
  },
  {
    "code": "GTQ",
    "name": "الكتزال الغواتيمالي",
    "symbol": "Q",
    "flag": "GT",
  },
  {
    "code": "GYD",
    "name": "الدولار الغياني",
    "symbol": "\$",
    "flag": "GYD",
  },
  {
    "code": "HTG",
    "name": "جوردة هايتية",
    "symbol": "G",
    "flag": "HTI",
  },
  {
    "code": "ISK",
    "name": "الكرونة الآيسلندي",
    "symbol": "kr",
    "flag": "ISK",
  },
  {
    "code": "JMD",
    "name": "الدولار الجاميكي",
    "symbol": "J\$",
    "flag": "JMD",
  },
  {
    "code": "JOD",
    "name": "الدينار الأردني",
    "symbol": "د.أ",
    "flag": "JO",
  },
  {
    "code": "KZT",
    "name": "التينغ الكازاخستاني",
    "symbol": "〒",
    "flag": "KZT",
  },
  {
    "code": "KES",
    "name": "الشيلينغ الكيني",
    "symbol": "KSh",
    "flag": "KES",
  },
  {
    "code": "KWD",
    "name": "الدينار الكويتي",
    "symbol": "د.ك",
    "flag": "KWD",
  },
  {
    "code": "KGS",
    "name": "سوم قرغيزستاني",
    "symbol": "с",
    "flag": "KG",
  },
  {
    "code": "LAK",
    "name": "كيب لاوي",
    "symbol": "₭",
    "flag": "LAK",
  },
  {
    "code": "LRD",
    "name": "الدولار الليبيري",
    "symbol": "\$",
    "flag": "LRD",
  },
  {
    "code": "MKD",
    "name": "الدينار المقدوني",
    "symbol": "ден",
    "flag": "MKD",
  },
  {
    "code": "MWK",
    "name": "الكواشا الملاوية",
    "symbol": "MK",
    "flag": "MWK",
  },
  {
    "code": "MUR",
    "name": "الروبية الموريشيوسية",
    "symbol": "₨",
    "flag": "MUR",
  },
  {
    "code": "MDL",
    "name": "الليو المولدوفي",
    "symbol": "L",
    "flag": "MDL",
  },
  {
    "code": "MNT",
    "name": "التوغروغ المنغولي",
    "symbol": "₮",
    "flag": "MNT",
  },
  {
    "code": "MAD",
    "name": "الدرهم المغربي",
    "symbol": "MAD",
    "flag": "MAD",
  },
  {
    "code": "MZN",
    "name": "المتكال الموزمبيقي",
    "symbol": "MT",
    "flag": "MZN",
  },
  {
    "code": "MMK",
    "name": "الكيات الميانماري",
    "symbol": "Ks",
    "flag": "MM",
  },
  {
    "code": "NAD",
    "name": "دولار ناميبيا",
    "symbol": "\$",
    "flag": "NAD",
  },
  {
    "code": "NPR",
    "name": "الروبية النيبالية",
    "symbol": "₨",
    "flag": "NPR",
  },
  {
    "code": "NIO",
    "name": "كوردبا نيكاراغوا",
    "symbol": "C\$",
    "flag": "NIO",
  },
  {
    "code": "NGN",
    "name": "النيرة النيجيرية",
    "symbol": "₦",
    "flag": "NGN",
  },
  {
    "code": "OMR",
    "name": "الريال العماني",
    "symbol": "﷼",
    "flag": "OMR",
  },
  {
    "code": "PKR",
    "name": "الروبية الباكستانية",
    "symbol": "₨",
    "flag": "PKR",
  },
  {
    "code": "PEN",
    "name": "السول البيروفي",
    "symbol": "S/.",
    "flag": "PEN",
  },
  {
    "code": "QAR",
    "name": "الريال القطري",
    "symbol": "﷼",
    "flag": "QAR",
  },
  {
    "code": "RWF",
    "name": "الفرنك الرواندي",
    "symbol": "FRw",
    "flag": "RWA",
  },
  {
    "code": "RSD",
    "name": "الدينار الصربي",
    "symbol": "Дин.",
    "flag": "RSD",
  },
  {
    "code": "SCR",
    "name": "الروبية السيشلية",
    "symbol": "₨",
    "flag": "SC",
  },
  {
    "code": "SOS",
    "name": "الشلن الصومالي",
    "symbol": "S",
    "flag": "SOS",
  },
  {
    "code": "LKR",
    "name": "الروبية السريلانكية",
    "symbol": "₨",
    "flag": "LKR",
  },
  {
    "code": "SYP",
    "name": "الليرة السورية",
    "symbol": "LS",
    "flag": "SYP",
  },
  {
    "code": "TZS",
    "name": "الشلن التنزاني",
    "symbol": "TSh",
    "flag": "TZS",
  },
  {
    "code": "TND",
    "name": "الدينار التونسي",
    "symbol": "د.ت",
    "flag": "TN",
  },
  {
    "code": "UGX",
    "name": "الشيلينغ الأوغندي",
    "symbol": "USh",
    "flag": "UGX",
  },
  {
    "code": "UAH",
    "name": "الهريفنا الأوكرانية",
    "symbol": "₴",
    "flag": "UAH",
  },
  {
    "code": "UYU",
    "name": "بيزو أوروغواي",
    "symbol": "\$U",
    "flag": "UYU",
  },
  {
    "code": "VEF",
    "name": "البوليفار الفنزويلي",
    "symbol": "Bs",
    "flag": "VEF",
  },
  {
    "code": "YER",
    "name": "الريال اليمني",
    "symbol": "﷼",
    "flag": "YER",
  },
  {
    "code": "ZMW",
    "name": "الكواشا الزامبي",
    "symbol": "ZK",
    "flag": "ZM",
  },
];
